<?php
return array(
    'get_apk_need_package_name' => array(
        'com.hola.launcher',
        'net.one97.paytm',
        'com.man.wire',
        'com.mile.brain',
        'com.airtel.ng.android.music',
        'com.opera.mini.native',
        'com.kelltontech.maxisgetit',
        'com.igg.android.im',
        'ru.yandex.searchplugin',
        'com.find.opposite',
        'com.onavo.android.onavoid',
        'com.onavo.android.onavoid',
        'escapemusic.android.a049jalvarez',
        'com.onavo.android.onavoid',
        'com.airtel.ng.android.music',
        'com.onavo.android.onavoid',
        'com.igg.android.im',
        'com.eterno',
        'com.opera.mini.native',
        'com.onavo.android.onavoid',
        'com.lazada.android',
        'com.onavo.android.onavoid',
        'com.opera.max.global',
        'com.kpt.xploree.app ',
        'com.hungama.myplay.activity',
        'com.yeecall.app',
        'com.halo.wifikey.wifilocating',
        'com.kloudpeak.gundem',
        'com.soft.blued',
        'com.onavo.android.onavoid',
        'in.redbus.android',
        'com.alibaba.aliexpresshd',
        'com.leo.appmaster',
        'com.guvera.android',
        'com.igg.android.im',
        'com.madridmola.tabbarcontrol',
        'me.everything.launcher',
        'com.jumia.android',
        'com.coco.aom.thai',
        'com.baidu.Funnypopularvideos',
        'com.igg.android.im',
        'com.alibaba.aliexpresshd',
        'com.ucool.hero',
        'com.pedidosya',
    ),
    
    'RingtonePartner' => array(
            'advertiser_image_api' => 'https://secure.mappstreet.com/creatives_api/action/KW5qKytxd2VmeX1~f0BqbHZw?campaign_ids=',
     ),
    //55,25 * * * * cd /data/wwwroot/dev/phpfw/tools/SyncOfferProject/Sh/ && /bin/bash /data/wwwroot/dev/phpfw/tools/SyncOfferProject/Sh/SyncOfferRun.sh 'TouchPalSupersonicSyncAction' 'sync_TouchPalSupersonic' 'pub' >> /data/adn_logs/access/sync_offer_project_log/sync_crontab_monitor/sync_TouchPalSupersonic/sync_log_$(date +\%Y_\%m_\%d).log 2>&1
    'cron_sync_offer_command' => "cd /data/wwwroot/{project_folder}/phpfw/tools/SyncOfferProject/Sh/ && /bin/bash /data/wwwroot/{project_folder}/phpfw/tools/SyncOfferProject/Sh/SyncOfferRun.sh '{sync_action}' '{sync_folder}' '{pub_or_not}' >> {sync_log_file_dir} 2>&1",
    
);
