<?php

global $SYNC_ANALYSIS_GLOBAL;
$SYNC_ANALYSIS_GLOBAL = array(
    'source' => '',
    'advertiser_id' => '',
    'advertiser_name' => '',
    'run_begin_time' => '',
    'run_end_time' => '',
    'tmp_check_logic_run_time' => 0,
    'run_time' => 0,
    'api_logic_run_time' => 0,
    'convert_logic_run_time' => 0,
    'data_model_logic_run_time' => 0,
    'creative_logic_run_time' => 0,
    'network_id' => '',
    'user_id' => '',
    'select' => 0,
    'select_mysql' => 0,
    'insert' => 0,
    'update' => 0,
    'update_trackurl' => 0,
    'update_status' => 0,
    'advertisere_offers' => 0,
    'pause_offers' => 0,
    'restart_offers' => 0,
	'dailycap_restart_offers' => 0,
    'insert_creatives' => 0,
    'update_creatives' => 0,
    'curl_time' => 0,
    'curl_success' => 0,
    'curl_fail' => 0,
    'queue_time' => 0,
    'memory_get_usage' => '',
    'memory_get_peak_usage' => '',
);